### ISSUE TITLE
Affiliation form do not works with some characters.

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#241] opened 2017-08-10 18:43 UTC
Try to write São Paulo in the affiliation name.

![screen shot 2017-08-10 at 15 41 58](https://user-images.githubusercontent.com/504142/29186346-965f0c50-7de2-11e7-93f0-c569f75100fb.png)

**Comment by michael** [comment] 2017-08-11 10:40
Thanks @fabiobatalha! 

I can confirm this on my Mac when holding down the a key and then selecting ã. Copy and pasting São Paulo works. @oliver---- what kind of problem is this? Not the same as handling dead keys right?

**Comment by oliver----** [comment] 2017-08-11 12:19
I am not sure if you are both talking about the same problem. I can confirm that the OSX special character menu generates extra characters, but it sounds like @fabiobatalha is not able to type ã at all.

**Comment by oliver----** [comment] 2017-08-11 12:20
@fabiobatalha in which way are you generating this character?

**Comment by oliver----** [comment] 2017-08-11 12:28
@michael under OSX this is actually a `composition-start` issue.

**Comment by oliver----** [comment] 2017-08-11 12:40
Interestingly, OSX only fires `compositionstart` only if you navigate the context menu via cursor, not when using the mouse or the accellerators.

**Comment by oliver----** [comment] 2017-08-11 13:11
This demonstrates four ways of entering it on OSX with German keyboard:
![texture-special-character-issues](https://user-images.githubusercontent.com/284099/29214227-cf53461a-7ea6-11e7-86eb-28c9faf2b70e.gif)
1. via `~`,`a`
2. via hold `a`, then `->` and `ENTER` to select
3. via hold `a`, then mouse click
4. via hold `a `, then accellerator

1. and 2. are working
3. and 4. are creating an extra character, because there is no sign that the character inserted first, before opening the special-character menu, is overwritten.

**Comment by fabiobatalha** [comment] 2017-08-11 13:49
@oliver---- @michael 

This is what happens with me. It is an OSX U.S. International - PC

![sao](https://user-images.githubusercontent.com/504142/29215758-a3fcdf68-7e82-11e7-97cb-4d3febafd5c5.gif)

1. S
S
2. ~, a (shift+~, a)
Sã
3. o
So

**Comment by oliver----** [comment] 2017-08-11 14:16
So it is basically the classical composition. Strange... I will try to change the keyboard settings, and see if I can reproduce it locally.

**Comment by oliver----** [comment] 2017-08-11 14:26
Unfortunately, it works locally for me with U.S. setting. 
We will need to create a bundle with some logging, so I can understand this a bit more.

**Comment by oliver----** [comment] 2017-08-11 14:38
@fabiobatalha Are you using Firefox?
At least I just found that this is not working in Firefox.

**Comment by oliver----** [comment] 2017-08-11 14:47
In addition to that I just found a variety of other problems in Firefox.
@michael can you add something to check the browser, and let us block other browsers than Chrome for a while?
We will try to bring back Firefox support, but regarding Texture, this is not high priority. It was working way better than it is currently, and I am not aware of any changes in that regard on our side.

**Comment by fabiobatalha** [comment] 2017-08-11 15:05
@michael @oliver---- 

The ã is working on Chrome.

**Comment by oliver----** [comment] 2017-08-11 18:08
I close this, as it is a general Firefox issue, which we have tracked.

**Closed by oliver----** 2017-08-11 18:08 UTC
Labels: bug
