### ISSUE TITLE
Ability to use an image as table

### ISSUE THREAD

**Issue by fabiobatalha** [substance/texture#1168] opened 2019-02-11 18:00 UTC
As a production assistent, I want to be able to include tables as images.

**Comment by fabiobatalha** [comment] 2019-02-12 17:27
Related to: #626

**Comment by oliver----** [comment] 2019-02-12 23:34
I think we should keep these as open.

**Comment by oliver----** [comment] 2019-02-12 23:35
Closing this because it is duplicate of #626

**Closed by oliver----** 2019-02-12 23:35 UTC
Labels: erudit
