### ISSUE TITLE
Error saving documents on desktop app (macOS 10.14.2)

### ISSUE THREAD

**Issue by hyglac** [substance/texture#1126] opened 2019-01-30 01:43 UTC
Hi, I want to report the following error; I'm not sure whether you're aware of it. Basically, it doesn't save changes and I have to exit Texture without edits made. Also, footnotes are not created.

Uncaught Exception:
Error: Object has been destroyed
    at EventEmitter.ipcMain.once (/Applications/Texture.app/Contents/Resources/app/main.js:148:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Applications/Texture.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

**Comment by oliver----** [comment] 2019-01-30 09:57
Thanks!

We are currently about to work on the next release. And we will take a look at this.

**Comment by Integral** [comment] 2019-02-06 09:21
I will close this issue since I can not reproduce it within upcoming Texture 2.0 app.
@hyglac I would be very grateful if you could try our [preview release](https://github.com/substance/texture/releases/tag/v2.0.0-preview.1) and open a new issue if you find any saving problems.

**Closed by Integral** 2019-02-06 09:21 UTC
Labels: bug
