### ISSUE TITLE
output xml on save is not working.Its not fetching title from node

### ISSUE THREAD

**Issue by vishnukpkp** [substance/texture#260] opened 2017-09-08 11:37 UTC

**Comment by vishnukpkp** [comment] 2017-09-08 11:40
Cannot read property 'getTextPath' of undefined
    at FigComponent.render (FigComponent.js:45)
    at _capture (RenderingEngine.js:200)
    at DescendingContext._createComponent (RenderingEngine.js:685)
    at IsolatedNodeComponent.renderContent (AbstractIsolatedNodeComponent.js:63)
    at IsolatedNodeComponent.render (IsolatedNodeComponent.js:66)
    at _capture (RenderingEngine.js:242)
    at DescendingContext._createComponent (RenderingEngine.js:685)
    at TextureContainerEditor._renderNode (TextureContainerEditor.js:25)
    at TextureContainerEditor.<anonymous> (ContainerEditor.js:95)
    at Array.forEach (<anonymous>)

**Comment by axfelix** [comment] 2017-09-12 16:38
Hi @vishnukpkp -- this is an issue with how Texture handles our `<fig>` output currently, so it's a duplicate of https://github.com/substance/texture/issues/252 which you've already commented on.

**Comment by vishnukpkp** [comment] 2017-09-14 05:12
Hi,

Is there a chance that u fix this issue soon and make an other commit.
Because i'm integrating this project with mine.So it will be really helpful.

Thank u

**Comment by michael** [comment] 2017-09-15 16:51
Will be fixed in next release, but added some comments in how you can work around (#252)

**Closed by michael** 2017-09-15 16:51 UTC
