### ISSUE TITLE
Manifest.xml requirement

### ISSUE THREAD

**Issue by axfelix** [substance/texture#456] opened 2018-03-26 16:38 UTC
Hi guys,

Just to confirm -- is it necessary to pass a manifest.xml along with document.xml when importing documents into Texture in every case? This doesn't seem right (I think the goal is to be able to open any compliant DarArticle JATS file directly) but we're getting a little confused when integrating the newest version into OJS.

**Comment by michael** [comment] 2018-03-27 10:54
Yes currently it is necessary, as we can't guess how for instance image urls etc. are resolved. As an integrator you can dynamically compute the manifest file using your conventions.

I suppose you are currently storing the JATS XML in the database, and now want a way to open in Texture. This can be achieved by implementing an HTTP endpoint that returns a valid RawArchive JSON structure. See here: https://github.com/substance/texture/blob/master/docs/steps/0004-persistence.md#raw-archive

You may also want to consider storing documents on the file system instead of the database. Then in a future version you could benefit from Git versioning (each time you hit save a new version get stored).

We are very busy this week, but could help you with that next week in a call or so.

**Comment by kaschioudi** [comment] 2018-03-29 13:53
Hi @michael ,

thank you for you reply. 

I am still under the process of integrating OTS with Texture 1.0.0-preview.1. At the moment, I am having hard time displaying images in the editor. Could you please tell me why images are not displaying with this attached JSON file? 

[egg_comic2.txt](https://github.com/substance/texture/files/1860362/egg_comic2.txt)

**Comment by kaschioudi** [comment] 2018-03-29 13:57
I have also tried from electron desktop add with luck. I broke down this JSON file into `manifest.xml`, `manuscript.xml` + images. (please not that i tried to put all the images in the root folder first and then inside a media folder).

**Comment by michael** [comment] 2018-04-06 10:27
Sorry this is a bit hard to resolve without more context. I assume you are working on a custom endpoint implemented in PHP?

The general concept is that the endpoint returns a valid image url (you can store it wherever you want).

You can see a working example by starting the dev server and opening: http://localhost:4000/archives/kitchen-sink

![image](https://user-images.githubusercontent.com/2931/38416652-b418a322-3995-11e8-856a-3ac136a87ae2.png)

**Comment by kaschioudi** [comment] 2018-04-10 19:18
hi @michael ,

> Sorry this is a bit hard to resolve without more context. 

Which additional information do you need? 

Did you look at the attached json file above? (note: I have replaced the URL of my OTS install with `www.domain.com` but I could email you the complete URL so that you can try yourself since the images URL are valid and accessible from Internet.)

**Comment by michael** [comment] 2018-04-10 20:50
Hi @kaschioudi 

There are many ways to approach resolving images and where to store the XML and generating the manifest. I don't know how you are doing it currently. Have you written a script in PHP that implements the RawArchive endpoint or are you using our implementation from dar-server?

The file you attached is invalid JSON. However I see that there are some escaped slashes, maybe there's the problem. But since i don't know your integration I can only guess....

```
"media\/image2.png":{"encoding":"url","data":"http:\/\/www.domain.com\/manager\/json\/id\/3819\/media\/image2.png","size":235999,"createdAt":1522075446,"updatedAt":1522075446}
```

**Comment by kaschioudi** [comment] 2018-04-11 14:33
Hi @michael,

> There are many ways to approach resolving images and where to store the XML and generating the manifest. I don't know how you are doing it currently

I have configured the editor to use `substance.HttpStorageClient(storageUrl)` where `storageUrl` points to a URL which return a document archive created based on the OTS job conversion ID submitted in the URL. The document I have attached above is an example of returned JSON document. 

Based on your previous comment, I have made changes so that `json_encode` does not escape slashes `json_encode($data, JSON_UNESCAPED_SLASHES)`.

> The file you attached is invalid JSON. 

Beside escaped slashes which other issues have you identified? I am asking because the content of the file is valid JSON as per https://jsonlint.com. 

That being said, escaping slashes does not seem to fix the problem. I am attaching an example of Document Archive generated from my script with slashes not escaped. Please note that I have also replaced images paths with images placeholder from internet (eg. https://picsum.photos/300/300/?image=10). Could you please try to load the attached file below and tell me why the images are still not loading? 

thank you for your assistance.

[egg-comics-noescape-picumimages.txt](https://github.com/substance/texture/files/1899244/egg-comics-noescape-picumimages.txt)

**Comment by oliver----** [comment] 2018-04-12 10:51
@kaschioudi Thanks for the information. I am looking into it.

**Comment by oliver----** [comment] 2018-04-20 05:52
Hey @kaschioudi,
I think the problem is that the assets are not within the "resources" block:
I.e. move these
```
"media/image1.png": {
    "encoding": "url",
    "data": "https://picsum.photos/300/300/?image=10",
    "size": 0,
    "createdAt": 0,
    "updatedAt": 0
  },
  "media/image2.png": {
    "encoding": "url",
    "data": "https://picsum.photos/300/300/?image=20",
    "size": 0,
    "createdAt": 0,
    "updatedAt": 0
  },
  "media/image3.png": {
    "encoding": "url",
    "data": "https://picsum.photos/300/300/?image=30",
    "size": 0,
    "createdAt": 0,
    "updatedAt": 0
  },
  "media/image4.png": {
    "encoding": "url",
    "data": "https://picsum.photos/300/300/?image=40",
    "size": 0,
    "createdAt": 0,
    "updatedAt": 0
  }
```
into `"resources": {...}`, where e.g. `manifest.xml` is defined..

**Comment by kaschioudi** [comment] 2018-04-26 12:55
thanks @oliver---- , it's working!

**Closed** 2018-11-14 19:21 UTC
