### ISSUE TITLE
Table cells should wrap text always

### ISSUE THREAD

**Issue by michael** [substance/texture#895] opened 2018-09-19 13:39 UTC
Reported by Giuliano.

We should prevent from such scenarios:

![image](https://user-images.githubusercontent.com/2931/45756812-21fdef00-bc22-11e8-9c14-c3ae7518ed6b.png)

Reproduce:

- insert a new table in Manuscript view
- add a long URL into one of the cells
- open Metadata view
- go to tables
There the table cells are not wrapped.

**Comment by oliver----** [comment] 2018-09-19 13:41
@Integral this seems to be a CSS thingie. Could you help here?

**Comment by Integral** [comment] 2018-09-19 21:07
I can't reproduce it.

**Comment by oliver----** [comment] 2018-09-19 21:09
Looks like they have some long urls in the text.

**Comment by oliver----** [comment] 2018-09-19 21:11
Can't reproduce neither.

**Comment by Integral** [comment] 2018-09-19 21:11
@oliver---- i've tried long urls in chrome and electron... Everything is ok for me
![screen shot 2018-09-20 at 00 11 25](https://user-images.githubusercontent.com/182010/45781799-bfc8dc80-bc69-11e8-96ba-0aa6692d1c66.png)

**Comment by oliver----** [comment] 2018-09-19 21:12
@michael do you have more details about this?

**Comment by oliver----** [comment] 2018-09-19 21:12
@Integral let's wait then

**Comment by oliver----** [comment] 2018-09-20 14:16
@michael also here you are needed

**Comment by michael** [comment] 2018-09-20 15:31
Also can't reproduce.

@gmaciocci can you provide the steps you did to end up with the broken table layout?

**Comment by oliver----** [comment] 2018-09-20 17:27
@gmaciocci Thx! now I can see it 😄

**Comment by oliver----** [comment] 2018-09-20 17:27
@michael @Integral this seems to be a CSS thing.

**Comment by oliver----** [comment] 2018-09-20 17:30
Added a 'Reproduce' to the issue description

**Comment by oliver----** [comment] 2018-09-20 17:31
@Integral do you think you can fix this?

**Comment by Integral** [comment] 2018-09-20 20:08
Will look into this

**Comment by Integral** [comment] 2018-09-20 22:03
Fixed via c5be87c.

**Comment by oliver----** [comment] 2018-09-20 22:04
THX!

**Closed by Integral** 2018-09-20 22:03 UTC
